-- Generated by Oracle SQL Developer REST Data Services 21.2.1.204.1703
-- Exported REST Definitions from ORDS Schema Version 24.3.0.r2620924

DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'WKSP_RUMA01W1',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'api',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'c2r-v1',
      p_base_path      => '/v1/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'c2r-v1',
      p_pattern        => 'personas',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'c2r-v1',
      p_pattern        => 'personas',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'declare 
      li_status_code   integer;
      lcl_request      CLOB    := :body_text;
      lcl_response     CLOB;

begin  
    SP_API_INSERTARPERSONA(icl_request     => lcl_request 
                          ,ocl_response    => lcl_response
                          ,on_status_code  => li_status_code); 
    :status_code := li_status_code;
    htp.prn(lcl_response);                   
end;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'c2r-v1',
      p_pattern        => 'personas',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'declare 
      li_status_code   integer;
      lcl_request      CLOB    := :body_text;
      lcl_response     CLOB;

begin  
    SP_API_ACTUALIZARPERSONA(icl_request     => lcl_request 
                            ,ocl_response    => lcl_response
                            ,on_status_code  => li_status_code); 
    :status_code := li_status_code;
    htp.prn(lcl_response);                   
end;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'c2r-v1',
      p_pattern        => 'personas/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'c2r-v1',
      p_pattern        => 'personas/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'declare
    lv_json varchar2(4000);
begin
    OWA_UTIL.mime_header(''application/json'');
    update personas a
    set a.estado = ''INACTIVO''
    where a.id = :id;
    if sql%rowcount > 0 then
        commit;
        lv_json := ''{
                   "codigo_respuesta": 0,
                   "categoria_respuesta": null,
                   "descripcion_excepcion": null,
                   "descripcion_tecnica": null
                   }'';
        --dbms_output.put_line(''0: '' || lv_json);                   
    else
        lv_json := ''{
                   "codigo_respuesta": -1,
                   "categoria_respuesta": 1020,
                   "descripcion_excepcion": "No existe registro para eliminar",
                   "descripcion_tecnica": null
                   }'';
        --.put_line(''1: '' || lv_json);                   
    end if;
    :status_code := 200;
    htp.prn(lv_json);                          
exception
    when others then
        rollback;
        lv_json := ''{
                   "codigo_respuesta": -1,
                   "categoria_respuesta": 1040,
                   "descripcion_excepcion": "Ha ocurrido un error al eliminar el registro",
                   "descripcion_tecnica": "'' || REPLACE(substr(sqlerrm,1,150),''"'') ||'' 
                   }'';
    --dbms_output.put_line(''-1: '' || lv_json); 
    :status_code := 200;
    htp.prn(lv_json);                          
end;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'c2r-v1',
      p_pattern        => 'personas/:id',
      p_method         => 'GET',
      p_source_type    => 'json/item',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from personas where id = :id and estado = ''ACTIVO'''
      );

  ORDS.CREATE_ROLE(p_role_name  => 'personas_role');

  l_roles(1)   := 'personas_role';
  l_modules(1) := 'c2r-v1';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'personas_privilige',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'personas_privilige',
      p_description    => '',
      p_comments       => NULL);      


  COMMIT; 

END;