openapi: 3.0.0
info:
  title: ORDS generated API for c2r-v1
  version: 1.0.0
servers:
  - url: >-
      https://gf14df869413d1f-ruma01.adb.us-ashburn-1.oraclecloudapps.com/ords/api/v1/
paths:
  /personas:
    put:
      description: Create or update a record on c2r-v1
      security:
        - BasicAuth: []
        - BearerAuth: []
        - OAuth2: []
      responses:
        '200':
          description: The successfully updated record.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '201':
          description: The successfully created record.
          content:
            application/json:
              schema:
                type: object
                properties: {}
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1_ITEM'
    post:
      description: Create a new record on c2r-v1
      security:
        - BasicAuth: []
        - BearerAuth: []
        - OAuth2: []
      responses:
        '201':
          description: The successfully created record.
          content:
            application/json:
              schema:
                type: object
                properties: {}
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1_ITEM'
  /personas/{id}:
    get:
      description: Retrieve a record from c2r-v1
      security:
        - BasicAuth: []
        - BearerAuth: []
        - OAuth2: []
      responses:
        '200':
          description: The queried record.
          content:
            application/json:
              schema:
                type: object
                properties:
                  apellidos:
                    $ref: '#/components/schemas/VARCHAR2'
                  email:
                    $ref: '#/components/schemas/VARCHAR2'
                  estado:
                    $ref: '#/components/schemas/VARCHAR2'
                  id:
                    $ref: '#/components/schemas/NUMBER'
                  identificacioncompleta:
                    $ref: '#/components/schemas/VARCHAR2'
                  nombrecompleto:
                    $ref: '#/components/schemas/VARCHAR2'
                  nombres:
                    $ref: '#/components/schemas/VARCHAR2'
                  numeroidentificacion:
                    $ref: '#/components/schemas/VARCHAR2'
                  salario:
                    $ref: '#/components/schemas/NUMBER'
                  tipoidentificacion:
                    $ref: '#/components/schemas/VARCHAR2'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: ^[^/]+$
          description: implicit
    delete:
      description: Remove a record from c2r-v1
      security:
        - BasicAuth: []
        - BearerAuth: []
        - OAuth2: []
      responses:
        '204':
          description: Deleted result.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: ^[^/]+$
          description: implicit
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: >-
            https://gf14df869413d1f-ruma01.adb.us-ashburn-1.oraclecloudapps.com/ords/api/oauth/auth
          scopes: {}
        authorizationCode:
          authorizationUrl: >-
            https://gf14df869413d1f-ruma01.adb.us-ashburn-1.oraclecloudapps.com/ords/api/oauth/auth
          tokenUrl: >-
            https://gf14df869413d1f-ruma01.adb.us-ashburn-1.oraclecloudapps.com/ords/api/oauth/token
          scopes: {}
        clientCredentials:
          tokenUrl: >-
            https://gf14df869413d1f-ruma01.adb.us-ashburn-1.oraclecloudapps.com/ords/api/oauth/token
          scopes: {}
  schemas:
    NUMBER:
      type: number
    STRING:
      type: string
    VARCHAR2:
      type: string
    v1_ITEM:
      properties:
        body_text:
          type: string
