CREATE OR REPLACE EDITIONABLE TRIGGER "WKSP_RUMA01W1"."TRG_PERSONAS_NOMBRES_APELLIDOS" 
BEFORE INSERT  OR UPDATE ON PERSONAS 
FOR EACH ROW
BEGIN
    IF INSERTING OR UPDATING THEN
        :NEW.NOMBRES    := UPPER(:NEW.NOMBRES);
        :NEW.APELLIDOS  := UPPER(:NEW.APELLIDOS);
    END IF;    
END;
/
